version : '3.8'
services:
  boathouse-mysql:
    image: registry.cn-hangzhou.aliyuncs.com/smartide/mysql:8.0.21
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init-file=/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: mysql --user=root --password=P2ssw0rd -e 'SHOW DATABASES LIKE "BoatHouse";'
      interval: 3s
      timeout: 1s
      retries: 16
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: P2ssw0rd
    volumes:
      - './mysql/local:/docker-entrypoint-initdb.d'

  boathouse-phpmyadmin:
    image: registry.cn-hangzhou.aliyuncs.com/boathouse/phpmyadmin:5.0.4-apache
    restart: always
    expose:
      - 8090
    ports:
      - 8090:80
    environment:
      PMA_ARBITRARY: "1"