---

apiVersion: v1
kind: Pod
metadata:
  name: boathouse-dev
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
  labels:
    boathouse.service: boathouse
spec:
  runtimeClassName: sysbox-runc
  containers:
  - name: boathouse-dev
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-java-v2-vscode-vmlc:latest
    command: ["/sbin/init"]
    imagePullPolicy: Always
    resources:
      requests:
        memory: "3Gi"
        cpu: "1500m"
      limits:
        memory: "3Gi"
        cpu: "1500m"
    ports:
      - containerPort: 22
      - containerPort: 3000
      - containerPort: 8090
      - containerPort: 80
      - containerPort: 8080
      - containerPort: 8848

---

apiVersion: v1
kind: Service
metadata:
  name: boathouse-dev
spec:
  ports:
    - name: "tools-ssh-6822"
      port: 6822
      targetPort: 22
    - name: "tools-webide-vscode-6800"
      port: 6800
      targetPort: 3000
    - name: "tools-phpmyadmin-8090"
      port: 8090
      targetPort: 8090
    - name: "apps-boathouse-frontend"
      port: 4000
      targetPort: 4000
    - name: "apps-boathouse-backend"
      port: 8080
      targetPort: 8080
  selector:
    boathouse.service: boathouse
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: boathouse-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              boathouse/smartide-network: "true"
  podSelector:
    matchLabels:
      boathouse/smartide-network: "true"
