version: '3'

services:
  account-service-api-ci:
    image: maven:3.5.2-jdk-8-alpine
    volumes:
      - ../../../:/build
    working_dir: /build/src/account-service/api
    command: bash -c "mvn clean package spring-boot:repackage && mvn cobertura:cobertura"
