apiVersion: v1
kind: Service
metadata:
  name: account-service-api
  namespace: #{DEPLOY_K8S_NAMESPACE_PROD}#
spec:
  type: LoadBalancer
  ports:
  - port: 7002
    targetPort: 8080 
  selector:
    app: account-service-api

