apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: boathouse-prod
  labels:
    app: #{DEPLOY_K8S_NAMESPACE_PROD}#
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-db-deployment
  namespace: boathouse-prod
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: product-service-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: product-service-db
    spec:
      containers:
      - name: product-service-db
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "P2ssw0rd"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      imagePullSecrets:
      - name: regcred
  
