apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service-redis-deployment
  namespace: #{DEPLOY_K8S_NAMESPACE_PROD}#
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: statistics-service-redis
  strategy: {}
  template:
    metadata:
      labels:
        app: statistics-service-redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
