apiVersion: v1
kind: Service
metadata:
  name: statistics-service-worker
  namespace: #{DEPLOY_K8S_NAMESPACE_PROD}#
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: statistics-service-worker

