apiVersion: v1
kind: Service
metadata:
  name: statistics-service-redis
  namespace: #{DEPLOY_K8S_NAMESPACE_PROD}#
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app: statistics-service-redis
status:
  loadBalancer: {}
