apiVersion: v1
kind: Service
metadata:
  name: statistics-service-api
  namespace: #{DEPLOY_K8S_NAMESPACE_PROD}#
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: statistics-service-api