version: "3"
services:

    client:
        image: #{BOATHOUSE_CONTAINER_REGISTRY}#/#{BOATHOUSE_ORG_NAME}#/boat-house-frontend/client:latest
        restart: always
        ports:
            - 5000:8080
        networks:
            - frontend
            - backend

    management:
        image: #{BOATHOUSE_CONTAINER_REGISTRY}#/#{BOATHOUSE_ORG_NAME}#/boat-house-frontend/management:latest
        restart: always
        ports:
            - 5001:4000
        networks:
            - backend

networks:
    frontend:
        external: true
    backend:
        external: true

volumes:
    db-data:
