version: "3"
services:

    client:
        build: ./client
        restart: always
        ports:
            - 5000:8080
        networks:
            - frontend
            - backend

    management:
        build: ./management
        restart: always
        ports:
            - 5001:4000
        networks:
            - backend
            
networks:
    frontend:
    backend:

volumes:
    db-data: