apiVersion: v1
kind: Service
metadata:
  name: management
  namespace: #{DEPLOY_K8S_NAMESPACE_PROD}#
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 4000
  selector:
    app: management

