version: '3'

services:
  product-service-api-ci:
    image: maven:3.8.6-jdk-8
    volumes:
      - ../../../:/build
    working_dir: /build/src/product-service/api
    command: bash -c "mvn clean package spring-boot:repackage -Dmaven.test.skip=true"

