name: Build and Deploy dev statistics-service
on: 
  push:
    paths:
      - 'src/statistics-service/**'
      - '.github/workflows/statistics-service.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: list env
        run: env

      - name: docker build src/statistics-service/api
        run: docker build -f src/statistics-service/api/Dockerfile -t ${{ secrets.BOATHOUSE_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY}/statistics_service_api:action-${GITHUB_REF##*/}-ci-${GITHUB_RUN_NUMBER} -t ${{ secrets.BOATHOUSE_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY}/statistics_service_api:action-ci src/statistics-service/api 
 
      - name: docker build src/statistics-service/worker
        run: docker build -f src/statistics-service/worker/Dockerfile -t ${{ secrets.BOATHOUSE_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY}/statistics_service_worker:action-${GITHUB_REF##*/}-ci-${GITHUB_RUN_NUMBER} -t ${{ secrets.BOATHOUSE_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY}/statistics_service_worker:action-ci src/statistics-service/worker

      - name: docker images 
        run: docker images

      - name: docker login
        run : docker login ${{ secrets.BOATHOUSE_CONTAINER_REGISTRY }} -u ${{ secrets.CREDS_GITHUB_REGISTRY_USR }} -p ${{ secrets.packages_token }}

      - name: docker push statistics_service_api tag branch number
        run : docker push ${{ secrets.BOATHOUSE_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY}/statistics_service_api:action-${GITHUB_REF##*/}-ci-${GITHUB_RUN_NUMBER}
      
      - name: docker push statistics_service_api tag latest
        run: docker push ${{ secrets.BOATHOUSE_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY}/statistics_service_api:action-ci

      - name: docker push statistics_service_worker tag branch number
        run : docker push ${{ secrets.BOATHOUSE_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY}/statistics_service_worker:action-${GITHUB_REF##*/}-ci-${GITHUB_RUN_NUMBER}
      
      - name: docker push statistics_service_worker tag latest
        run: docker push ${{ secrets.BOATHOUSE_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY}/statistics_service_worker:action-ci

  deploy-k8s-test-github:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - name: list env
         run: env && ls

       - name: replace docker reg url（acr）
         run: sed -i "s|#{BOATHOUSE_CONTAINER_REGISTRY}#|${{ secrets.BOATHOUSE_CONTAINER_REGISTRY }}|g" devops/kompose/test/statistics-service-*.yaml

       - name: replace github org name
         run: sed -i "s|#{BOATHOUSE_ORG_NAME}#|${GITHUB_REPOSITORY_OWNER}|g" devops/kompose/test/statistics-service-*.yaml

       - name: replace rep branch name
         run: sed -i "s|#{env.BRANCH_NAME}#|action-${GITHUB_REF##*/}-ci|g" devops/kompose/test/statistics-service-*.yaml

       - name: replace BUILD ID
         run: sed -i "s|#{env.BUILD_ID}#|${GITHUB_RUN_NUMBER}|g" devops/kompose/test/statistics-service-*.yaml

       - name: replace k8s namespace
         run: sed -i "s|#{DEPLOY_K8S_NAMESPACE_TEST}#|${{ secrets.DEPLOY_K8S_NAMESPACE_TEST }}|g" devops/kompose/test/statistics-service-*.yaml

       - name: grep images url
         run: grep -i "image:" devops/kompose/test/statistics-service-*.yaml
         #run: ls devops/kompose/test/statistics-service-*.yaml  

       - uses: Azure/k8s-set-context@v1
         with:
           kubeconfig: ${{ secrets.KUBE_CONFIG }}

       - uses: Azure/k8s-create-secret@v1
         with:
           container-registry-url:  ${{ secrets.BOATHOUSE_CONTAINER_REGISTRY }}
           container-registry-username: ${{ secrets.CREDS_GITHUB_REGISTRY_USR }}
           container-registry-password: ${{ secrets.packages_token }}
           secret-name: demo-k8s-secret

       - uses: Azure/k8s-deploy@v1
         with:
           namespace: 'boathouse-test-github'
           manifests: |
              devops/kompose/test/statistics-service-api-deployment.yaml
              devops/kompose/test/statistics-service-api-svc.yaml
              devops/kompose/test/statistics-service-db-deployment.yaml
              devops/kompose/test/statistics-service-db-svc.yaml
              devops/kompose/test/statistics-service-redis-deployment.yaml
              devops/kompose/test/statistics-service-redis-svc.yaml
              devops/kompose/test/statistics-service-worker-deployment.yaml
              devops/kompose/test/statistics-service-worker-svc.yaml
           kubectl-version: 'latest'

