name: gitee-sync

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Use FTP deploy action to publish markdown into https://idcf.org.cn/boat-house
jobs:
  Sync-To-Gitee:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
        # 来源仓库
        source-repo: "git@github.com:idcf-boat-house/boat-house-backend.git"
        # 目标仓库
        destination-repo: "git@gitee.com:idcf-boat-house/boat-house-backend.git"
